### ISSUE TITLE
Make fails because of illegal OBO

### ISSUE THREAD

**Issue by matentzn** [microbial-conditions-ontology/Microbial-Conditions-Ontology#2]
Currently, your make process fails because you violate some OBO constraints. You can fix it by editing src/ontology/Makefile, and replacing the imports/*.obo goal with this:
```
imports/%_import.obo: imports/%_import.owl
#       $(OWLTOOLS) $(USECAT) $< -o -f obo $@
        $(ROBOT) convert --check false -i $< -o $@ # trying to use robot instead of owltools to avoid error "multiple def tags not allowed"
```
As you can see, it has a new clause (--check false), but it is otherwise unchanged. Let me know if that works!

**Comment by citmejia** [comment]
Hello,

It worked, but I had to to add the **--check false** clause to the **$(ONT).obo** goal too: 

$(ONT).obo: $(ONT).owl
	$(ROBOT) convert --check false -i $< -f obo -o $(ONT).obo.tmp && mv $(ONT).obo.tmp $@

Thanks!
